import { test, expect, describe } from 'bun:test'
import { readFileSync, existsSync } from 'node:fs'
import { VERSION } from '../src/version.js'
import { HELP, completionScript } from '../src/cli.js'

// Release-metadata sync. Every one of these mismatches has actually happened here:
//
//  - the published binaries and the download page both said 0.1.0 while the source had moved on,
//    so `dcxv version` could not distinguish two different builds
//  - a test asserted a hardcoded '0.1.0' and broke on the first version bump
//  - install.sh derived an asset name (dcxv-macos-x64) that build.sh never produced, so Intel
//    Macs were refused outright
//  - the README claimed "4 targets" after a fifth was added
//
// None of it is caught by anything that runs the CLI, so it is asserted directly here.

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))
const buildSh = readFileSync(new URL('../scripts/build.sh', import.meta.url), 'utf8')
// comment-stripped, so asserting on "code present" cannot be satisfied by a commented-out line
const buildShCode = buildSh.split('\n').filter(l => !/^\s*#/.test(l)).join('\n')
const readme = readFileSync(new URL('../README.md', import.meta.url), 'utf8')

// asset names straight out of build.sh's `build <bun-target> <asset>` lines
const BUILD_LINES = [...buildSh.matchAll(/^build\s+(\S+)\s+(\S+)\s*$/gm)].map(m => ({ target: m[1], asset: m[2] }))

describe('release sync — version', () => {
  test('src/version.js matches package.json', () => {
    // build.sh regenerates src/version.js from package.json, but `bun run build` (single target)
    // does not, so an out-of-band edit to either can desync the compiled binary from the release.
    expect(VERSION).toBe(pkg.version)
  })

  test('version is semver-shaped', () => {
    expect(VERSION).toMatch(/^\d+\.\d+\.\d+$/)
  })

  test('HELP advertises the same version', () => {
    expect(HELP).toContain(`v${VERSION}`)
  })

  test('src/version.js is generated, and says so', () => {
    const raw = readFileSync(new URL('../src/version.js', import.meta.url), 'utf8')
    expect(raw).toContain('generated by scripts/build.sh')
  })
})

describe('release sync — build targets', () => {
  test('build.sh builds a plausible set of targets', () => {
    expect(BUILD_LINES.length).toBeGreaterThanOrEqual(4)
    for (const { target, asset } of BUILD_LINES) {
      expect(target).toMatch(/^bun-(linux|darwin|windows)-(x64|arm64)(-musl)?$/)
      expect(asset).toMatch(/^dcxv-(linux|macos|windows)-(x64|arm64)(\.exe)?$/)
    }
  })

  test('asset names are unique and the windows one is the only .exe', () => {
    const assets = BUILD_LINES.map(b => b.asset)
    expect(new Set(assets).size).toBe(assets.length)
    for (const a of assets) expect(a.endsWith('.exe')).toBe(a.includes('windows'))
  })

  // The mapping install.sh performs: uname -s -> linux|macos, uname -m -> x64|arm64, then
  // "dcxv-$o-$a". Anything a user's machine can resolve to MUST be a name build.sh produces, or
  // the download 404s. dcxv-macos-x64 was missing exactly this way.
  test('every OS/arch combination install.sh can resolve is actually built', () => {
    const assets = new Set(BUILD_LINES.map(b => b.asset))
    for (const o of ['linux', 'macos']) {
      for (const a of ['x64', 'arm64']) {
        expect(assets.has(`dcxv-${o}-${a}`)).toBe(true)
      }
    }
    expect(assets.has('dcxv-windows-x64.exe')).toBe(true)   // documented as a manual download
  })

  test('build.sh writes SHA256SUMS covering the built assets', () => {
    expect(buildSh).toContain('SHA256SUMS')
    expect(buildSh).toMatch(/sha256sum\s+dcxv-\*/)
  })

  test('build.sh actually stamps the version into src/version.js, before compiling', () => {
    // must be live code that both reads package.json and writes src/version.js
    expect(buildShCode).toMatch(/package\.json/)
    expect(buildShCode).toMatch(/>\s*src\/version\.js/)
    const verIdx = buildShCode.indexOf('src/version.js')
    const firstBuild = buildShCode.indexOf('\nbuild ')
    expect(firstBuild).toBeGreaterThan(-1)
    expect(verIdx).toBeLessThan(firstBuild)   // stamped first, or the binaries carry a stale value
  })

  test('README documents every built platform', () => {
    for (const { asset } of BUILD_LINES) {
      const platform = asset.replace(/^dcxv-/, '').replace(/\.exe$/, '')
      expect(readme).toContain(platform)
    }
    // and does not claim a target count that contradicts build.sh
    const claimed = readme.match(/all (\d+) targets/)
    if (claimed) expect(Number(claimed[1])).toBe(BUILD_LINES.length)
  })
})

describe('release sync — help, completion and README agree on the command set', () => {
  // Commands are declared in three places: the dispatch switch, the COMMANDS completion string,
  // and HELP. A command missing from completion is invisible to tab-complete (`clusters` was),
  // and one missing from HELP is undiscoverable.
  const completion = completionScript('bash')
  const COMPLETION_WORDS = completion.match(/compgen -W "([^"]+)"/)[1].split(/\s+/)

  test('the completion word list is non-trivial and unique', () => {
    expect(COMPLETION_WORDS.length).toBeGreaterThan(15)
    expect(new Set(COMPLETION_WORDS).size).toBe(COMPLETION_WORDS.length)
  })

  test('every completed command appears in HELP', () => {
    // aliases are intentionally completed but not all separately documented
    const ALIASES = new Set(['products', 'ls', 'list', 'transactions', 'txns', 'history', 'help'])
    const missing = COMPLETION_WORDS.filter(w => !ALIASES.has(w) && !HELP.includes(`dcxv ${w}`))
    expect(missing).toEqual([])
  })

  test('every top-level command in HELP is completable', () => {
    const helpCmds = [...HELP.matchAll(/^\s{2}dcxv (\w[\w-]*)/gm)].map(m => m[1])
    expect(helpCmds.length).toBeGreaterThan(15)
    const missing = [...new Set(helpCmds)].filter(c => !COMPLETION_WORDS.includes(c))
    expect(missing).toEqual([])
  })

  test('all three shell completions embed the same command list', () => {
    for (const shell of ['zsh', 'fish']) {
      const s = completionScript(shell)
      for (const w of COMPLETION_WORDS) expect(s).toContain(w)
    }
  })
})

// dcxv-www is a separate repository, so these only run when it happens to be checked out
// alongside. Registered conditionally (rather than returning early) so an absent site repo shows
// as an explicit skip instead of a silent pass.
describe('release sync — published site assets', () => {
  const SITE = new URL('../../dcxv-www/', import.meta.url).pathname
  const installSh = SITE + 'static/cli/install.sh'
  const page = SITE + 'src/routes/[[lang]]/cli/+page.svelte'
  // shell "code" only: the removal rationale is written in a comment that names the old tool
  const codeOf = (sh) => sh.split('\n').filter(l => !/^\s*#/.test(l)).join('\n')

  const t = (cond, name, fn) => cond ? test(name, fn) : test.skip(`${name} (dcxv-www not checked out)`, () => {})

  t(existsSync(installSh), 'install.sh derives only asset names build.sh produces', () => {
    const code = codeOf(readFileSync(installSh, 'utf8'))
    expect(code).toContain('asset="dcxv-$o-$a"')
    // no leftover gate refusing a platform we now publish
    expect(code).not.toMatch(/Only macos-arm64/)
    // checksum verification must not invoke an unguarded external tool: awk was unguarded under
    // `set -e`, so a system with sha256sum but no awk aborted the install at exit 127
    expect(code).not.toMatch(/(^|[|(;&`$]\s*)awk\b/m)
    // and it must clean up after itself on every failure path
    expect(code).toMatch(/trap .* EXIT/)
  })

  t(existsSync(page), 'the download page lists exactly the built assets at the built version', () => {
    const src = readFileSync(page, 'utf8')
    expect(src.match(/const VERSION = '([^']+)'/)?.[1]).toBe(VERSION)
    const listed = [...src.matchAll(/file: '([^']+)'/g)].map(m => m[1]).sort()
    expect(listed).toEqual(BUILD_LINES.map(b => b.asset).sort())
  })
})
