#!/usr/bin/env bash
# Compile standalone dcxv binaries for all supported platforms with Bun.
# Output: dist/<asset> + dist/SHA256SUMS. Upload dist/* to https://dcxv.com/cli/.
set -euo pipefail
cd "$(dirname "$0")/.."

# Sync the embedded version from package.json so `dcxv version` is correct in the
# compiled binary (package.json is not on disk at runtime).
VER=$(bun -e 'console.log(require("./package.json").version)')
printf '// generated by scripts/build.sh — do not edit\nexport const VERSION = %s\n' "'$VER'" > src/version.js
echo "version: $VER"

mkdir -p dist
rm -f dist/dcxv-* dist/SHA256SUMS

build() { # <bun-target> <asset-name>
  echo "  building dist/$2  ($1)"
  bun build ./bin/dcxv.js --compile --target="$1" --outfile "dist/$2"
}

build bun-linux-x64      dcxv-linux-x64
build bun-linux-arm64    dcxv-linux-arm64
build bun-darwin-arm64   dcxv-macos-arm64
build bun-darwin-x64     dcxv-macos-x64
build bun-windows-x64    dcxv-windows-x64.exe

( cd dist && sha256sum dcxv-* > SHA256SUMS )
echo "done -> $(pwd)/dist/"
ls -1 dist
